routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes();
Route::get('/home', 'HomeController@index');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('partner', 'PartnerController');
    Route::resource('user', 'UserController'); 
    Route::get('/partnerexport', ['as' => 'partnerexport', 'uses' => 'PartnerController@export']);
});

resources/views/partials/alerts.blade.php
@if(Session::has('info'))
    <div class="row">
        <div class="col-md-12">
            <p class="alert alert-info">{{ Session::get('info') }}</p>
        </div>
    </div>
@endif

resources/views/partials/errors.blade.php
@if(count($errors->all()))
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-danger">
                <ul>
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
@endif

resources/views/partials/leftSideBar.blade.php
<aside id="leftsidebar" class="sidebar">
    <!-- User Info -->
    <div class="user-info">
        
        <div class="info-container">
            <div class="name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ $auth->name }}</div>
            <div class="email">{{ $auth->email }}</div>
            <div class="btn-group user-helper-dropdown">
                <i class="material-icons" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">keyboard_arrow_down</i>
                <ul class="dropdown-menu pull-right">
                     <li><a href="{{ url('/logout') }}"
                              onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                            <i class="material-icons">input</i>Sign Out</a>
                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                            {{ csrf_field() }}
                        </form>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- #User Info -->
    <!-- Menu -->
    <div class="menu">
        <ul class="list">
            <li class="header">MAIN NAVIGATION</li>
            @if(Auth::user()->is_active==0)         
            <li>
                <a href="{{ route('partner.index') }}">
                    <i class="material-icons">group</i>
                    <span>Profile Partner</span>
                </a>
            </li>
            @endif
            @if(Auth::user()->is_active==1)         
            <li>
            <a href="{{ route('user.index') }}">
                    <i class="material-icons">group</i>
                    <span>User</span>
                </a>
            </li>
            <li>
            <a href="{{ route('partnerexport') }}">
                    <i class="material-icons">exit_to_app</i>
                    <span>Export</span>
                </a>
            </li>
            @endif
            
            
            {{--<li>--}}
                {{--<a href="../../pages/typography.html">--}}
                    {{--<i class="material-icons">text_fields</i>--}}
                    {{--<span>Typography</span>--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="../../pages/helper-classes.html">--}}
                    {{--<i class="material-icons">layers</i>--}}
                    {{--<span>Helper Classes</span>--}}
                {{--</a>--}}
            {{--</li>--}}
        </ul>
    </div>
    <!-- #Menu -->
    <!-- Footer -->
    
    <!-- #Footer -->
</aside>
<!-- #END# Left Sidebar -->
<!-- Right Sidebar -->

resources/views/partials/navBar.blade.php
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand">Dealer Information System</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <!-- Call Search -->
                <!-- #END# Call Search -->
                <!-- Notifications -->
                <!-- <li class="dropdown">
                     <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                         <i class="material-icons">notifications</i>
                         <span class="label-count">7</span>
                     </a>
                     <ul class="dropdown-menu">
                         <li class="header">NOTIFICATIONS</li>
                         <li class="body">
                             <ul class="menu">
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-light-green">
                                             <i class="material-icons">person_add</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4>12 new members joined</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 14 mins ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-cyan">
                                             <i class="material-icons">add_shopping_cart</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4>4 sales made</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 22 mins ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-red">
                                             <i class="material-icons">delete_forever</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4><b>Nancy Doe</b> deleted account</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 3 hours ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-orange">
                                             <i class="material-icons">mode_edit</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4><b>Nancy</b> changed name</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 2 hours ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-blue-grey">
                                             <i class="material-icons">comment</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4><b>John</b> commented your post</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 4 hours ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-light-green">
                                             <i class="material-icons">cached</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4><b>John</b> updated status</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> 3 hours ago
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <div class="icon-circle bg-purple">
                                             <i class="material-icons">settings</i>
                                         </div>
                                         <div class="menu-info">
                                             <h4>Settings updated</h4>
                                             <p>
                                                 <i class="material-icons">access_time</i> Yesterday
                                             </p>
                                         </div>
                                     </a>
                                 </li>
                             </ul>
                         </li>
                         <li class="footer">
                             <a href="javascript:void(0);">View All Notifications</a>
                         </li>
                     </ul>
                 </li>-->
                <!-- #END# Notifications -->
                <!-- Tasks -->
                <!-- <li class="dropdown">
                     <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                         <i class="material-icons">flag</i>
                         <span class="label-count">9</span>
                     </a>
                     <ul class="dropdown-menu">
                         <li class="header">TASKS</li>
                         <li class="body">
                             <ul class="menu tasks">
                                 <li>
                                     <a href="javascript:void(0);">
                                         <h4>
                                             Footer display issue
                                             <small>32%</small>
                                         </h4>
                                         <div class="progress">
                                             <div class="progress-bar bg-pink" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 32%">
                                             </div>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <h4>
                                             Make new buttons
                                             <small>45%</small>
                                         </h4>
                                         <div class="progress">
                                             <div class="progress-bar bg-cyan" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 45%">
                                             </div>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <h4>
                                             Create new dashboard
                                             <small>54%</small>
                                         </h4>
                                         <div class="progress">
                                             <div class="progress-bar bg-teal" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 54%">
                                             </div>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <h4>
                                             Solve transition issue
                                             <small>65%</small>
                                         </h4>
                                         <div class="progress">
                                             <div class="progress-bar bg-orange" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 65%">
                                             </div>
                                         </div>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0);">
                                         <h4>
                                             Answer GitHub questions
                                             <small>92%</small>
                                         </h4>
                                         <div class="progress">
                                             <div class="progress-bar bg-purple" role="progressbar" aria-valuenow="85" aria-valuemin="0" aria-valuemax="100" style="width: 92%">
                                             </div>
                                         </div>
                                     </a>
                                 </li>
                             </ul>
                         </li>
                         <li class="footer">
                             <a href="javascript:void(0);">View All Tasks</a>
                         </li>
                     </ul>
                 </li>-->
                 <!-- #END# Tasks -->
                 </ul>
        </div>
    </div>
</nav>

resources/views/partials/page_loader.blade.php
<div class="page-loader-wrapper">
    <div class="loader">
        <div class="preloader">
            <div class="spinner-layer pl-red">
                <div class="circle-clipper left">
                    <div class="circle"></div>
                </div>
                <div class="circle-clipper right">
                    <div class="circle"></div>
                </div>
            </div>
        </div>
        <p>Please wait...</p>
    </div>
</div>

resources/views/partials/search_bar.blade.php
<div class="search-bar">
    <div class="search-icon">
        <i class="material-icons">search</i>
    </div>
    <input type="text" placeholder="START TYPING...">
    <div class="close-search">
        <i class="material-icons">close</i>
    </div>
</div>