routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes();
Route::get('/home', 'HomeController@index');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('partner', 'PartnerController');
    Route::resource('user', 'UserController'); 
    Route::get('/partnerexport', ['as' => 'partnerexport', 'uses' => 'PartnerController@export']);
});

app/Partner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Partner extends Model
{
    use SoftDeletes;
    public $table = "partner";

    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'full_name', 'code', 'mobile', 'size1', 'size2', 'size3', 'size4', 'size5',
        'size6', 'size7', 'size8', 'size9', 'pocket', 'kera_type', 'note'
    ];

    public function user(){
        return $this->belongsTo('App\User');
    }
}

app/Http/Controllers/PartnerController.php
<?php

namespace App\Http\Controllers;

use Request;
use Response;
use Redirect;
use App\Partner;
use App\User;
use Validator;
use Illuminate\Support\Facades\Auth;


class PartnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $partner = new Partner();
        return view('partner/form', compact('partner'))->with(['action' => 'add' ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        
        
        $input = Request::all();
        $validator = Validator::make(Request::all(), [
            'full_name' => 'required|min:5',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $partner = new Partner();
        $partner->full_name = $input['full_name'];
        $partner->user_id = Auth::user()->id;
        $partner->save();
        return redirect()->route('partner.edit',$partner->id)->with('info', 'User added, Name is: ' . $input['full_name']);

        }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $partner = Partner::find($id);
        return view('partner/form_edit', compact('partner'))->with(['action' => 'edit' ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $input = Request::all();
        $validator = Validator::make(Request::all(), [
            'full_name' => 'required|min:5',
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                        ->withErrors($validator)
                        ->withInput();
        }

        $partner = Partner::find($id);
        $partner->full_name = $input['full_name'];
        $partner->user_id = Auth::user()->id;
        $partner->save();
        return redirect()->route('partner.edit',$partner->id)->with('info', 'User edited, Name is: ' . $input['full_name']);

    }

    public function export(Request $request)
    {
        $headers = array(
            "Content-type" => "text/csv",
            "Content-Disposition" => "attachment; filename=file.csv",
            "Pragma" => "no-cache",
            "Cache-Control" => "must-revalidate, post-check=0, pre-check=0",
            "Expires" => "0"
        );
        
        $partners =Partner::with('user')->get();
        $columns = array('Full Name', 'Name');
        
        

        $callback = function() use ($partners, $columns)
        {
        $file = fopen('php://output', 'w');
        fputcsv($file, $columns);

        foreach($partners as $partner) {
            fputcsv($file, array($partner->full_name, $partner->user->name));
        }
        fclose($file);
        };
        return Response::stream($callback, 200, $headers);
    }   
}

resources/views/partner/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.errors')
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            @if($action=='edit')
                                Update Partner
                            @else
                                Create New Partner
                            @endif
                        </h2>

                    </div>
                    <div class="body">
                        <form id="form_validation" method="POST" action="{{ ($action=='edit')?route('partner.update', ['id' => $partner->id]):route('partner.store') }}">
                            @if($action=="edit")
                                {{ method_field('PUT') }}
                            @endif
                            {{ csrf_field() }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Full Name</label>
                                    <input type="text" class="form-control" name="full_name" id="form-full_name" value="{{ old('full_name') }}"  required>
                                </div>
                            </div>
                           
                            <button class="btn btn-success waves-effect" type="submit">SUBMIT</button>
                            </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function () {
            $('#form_validation').validate({
                rules: {
                    'checkbox': {
                        required: true
                    },
                    'gender': {
                        required: true
                    }
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
@endsection

resources/views/partner/form_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.errors')
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            @if($action=='edit')
                                Update Partner
                            @else
                                Create New Partner
                            @endif
                        </h2>

                    </div>
                    <div class="body">
                        <form id="form_validation" method="POST" action="{{ ($action=='edit')?route('partner.update', ['id' => $partner->id]):route('partner.store') }}">
                            @if($action=="edit")
                                {{ method_field('PUT') }}
                            @endif
                            {{ csrf_field() }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="full_name" id="form-name" value="{{ $partner->full_name }}" required>
                                </div>
                            </div>

                            <button class="btn btn-success waves-effect" type="submit">Update</button>
                            <a href="{{ route('partner.index') }}" class="btn btn-primary waves-effect">New</a>
                           
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function () {
            $('#form_validation').validate({
                rules: {
                    'checkbox': {
                        required: true
                    },
                    'gender': {
                        required: true
                    }
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
@endsection

resources/views/partner/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.alerts')
        <!-- Customers List -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                        Partners Profile
                        </h2>


                    </div>


                    <div class="body">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{{ route('customer.create') }}" class="btn btn-success pull-right">New Partners Profile</a>
                            </div>
                        </div>
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Code</th>
                                <th>Mobile #</th>
                            </tr>
                            </thead>
                            {{--<tfoot>--}}
                            {{--<tr>--}}
                                {{--<th>Name</th>--}}
                                {{--<th>Code</th>--}}
                                {{--<th>Phone</th>--}}
                                {{--<th>Action</th>--}}
                            {{--</tr>--}}
                            {{--</tfoot>--}}
                            <tbody>
                            @forelse ($customers as $customer)
                                <tr>
                                    <td><a href="{{ route('customer.edit', ['id' => $customer->id ]) }}"> {{ $customer->full_name }}</a></td>
                                    <td>{{ $customer->code }}</td>
                                    <td>{{ $customer->mobile }}</td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">No Record Found!</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples -->
    </div>
@endsection