routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes();
Route::get('/home', 'HomeController@index');
Route::group(['middleware' => 'auth'], function() {
    Route::resource('partner', 'PartnerController');
    Route::resource('user', 'UserController'); 
    Route::get('/partnerexport', ['as' => 'partnerexport', 'uses' => 'PartnerController@export']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function partners(){
        return $this->hasMany('App\Partner');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Request;
use Redirect;
use App\User;
use Validator;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //return User:: with('user')->get();
        //if(Auth::user()->id==3){
        $users = User::where('id', '!=', Auth::id())->get();

        //}
        
        return view('user/index', compact('users'));
        // $users = User:: with('user')->get();
        // $data['users'] = array();
        // foreach ($users as $var) {
        //     if($var->code !=''){
        //         $data['users'][$var->code] = array(
        //                 'name' => $var->full_name,
        //                 'phone' => $var->mobile,
        //                 'address' => '',
        //                 'size1' => $var->size1,
        //                 'size2' => $var->size2,
        //                 'size3' => $var->size3,
        //                 'size4' => $var->size4,
        //                 'size5' => $var->size5,
        //                 'size6' => $var->size6,
        //                 'size7' => $var->size7,
        //                 'size8' => $var->size8,
        //                 'size9' => $var->size9,
        //                 'pocket' => $var->pocket,
        //                 'keraType' => $var->kera_type,
        //                 'note' => $var->note,
        //                 'userId' => "03217548720"
        //             );
        //     }
            
        // }

        // echo json_encode($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();
        return view('user/form', compact('user'))->with(['action' => 'add' ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $input = Request::all();
        $validator = Validator::make(Request::all(), [
            'name' => 'required',
            'email' => 'required|email|unique:users',
            'password' => 'required',
            'c_password' => 'required|same:password'
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                        ->withErrors($validator)
                        ->withInput();
        }
        
        
        $user = new User();
        $user->name = $input['name'];
        $user->email = $input['email'];
        $user->password = bcrypt($input['password']);
        $user->save();
        return redirect()->route('user.index')->with('info', 'User added, Name is: ' . $input['name']);
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $users = User:: with('user')->whereUserId($id)->get();
        return $users;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::find($id);
        return view('user/form_edit', compact('user'))->with(['action' => 'edit' ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $input = Request::all();
        $validator = Validator::make(Request::all(), [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
        ]);

        if ($validator->fails()) {
            return Redirect::back()
                        ->withErrors($validator)
                        ->withInput();
        }
        
        $user = User::find($id);
        $user->name = $input['name'];
        $user->email = $input['email'];
        $user->save();
        
        return redirect()->route('user.index')->with('info', 'Customer edited, Name is: ' . $input['name']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        if (!$user) {
            session()->flash('msg', 'Required Data missing');
            return Redirect::back();
        }
        $user->delete();
        
        
        session()->flash('msg', 'Deleted');
        return Redirect::back();
    }
}

resources/views/user/form.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.errors')
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            @if($action=='edit')
                                Update User
                            @else
                                Create New User
                            @endif
                        </h2>

                    </div>
                    <div class="body">
                        <form id="form_validation" method="POST" action="{{ ($action=='edit')?route('user.update', ['id' => $user->id]):route('user.store') }}">
                            @if($action=="edit")
                                {{ method_field('PUT') }}
                            @endif
                            {{ csrf_field() }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="name" id="form-name" value="{{ old('name') }}" required>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Email</label>
                                    <input type="text" class="form-control" name="email" id="form-email" value="{{ old('email') }}" required>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Password </label>
                                    <input type="password" class="form-control" name="password" id="form-password" value="{{ $user->password }}">
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Confirm Password </label>
                                    <input type="password" class="form-control" name="c_password" id="form-c_password" value="{{ $user->c_password }}">
                                </div>
                            </div>

                            <button class="btn btn-success waves-effect" type="submit">Submit</button>
                            <a href="{{ route('user.index') }}" class="btn btn-primary waves-effect">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function () {
            $('#form_validation').validate({
                rules: {
                    'checkbox': {
                        required: true
                    },
                    'gender': {
                        required: true
                    }
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
@endsection

resources/views/user/form_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.errors')
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                            @if($action=='edit')
                                Update User
                            @else
                                Create New User
                            @endif
                        </h2>

                    </div>
                    <div class="body">
                        <form id="form_validation" method="POST" action="{{ ($action=='edit')?route('user.update', ['id' => $user->id]):route('user.store') }}">
                            @if($action=="edit")
                                {{ method_field('PUT') }}
                            @endif
                            {{ csrf_field() }}
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Name</label>
                                    <input type="text" class="form-control" name="name" id="form-name" value="{{ $user->name }}" required>
                                </div>
                            </div>

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <label>Email</label>
                                    <input type="text" class="form-control" name="email" id="form-email" value="{{ $user->email }}" required>
                                </div>
                            </div>

                            <button class="btn btn-success waves-effect" type="submit">Update</button>
                           <a href="{{ route('user.index') }}" class="btn btn-primary waves-effect">Back</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('scripts')
    <script>
        $(function () {
            $('#form_validation').validate({
                rules: {
                    'checkbox': {
                        required: true
                    },
                    'gender': {
                        required: true
                    }
                },
                highlight: function (input) {
                    $(input).parents('.form-line').addClass('error');
                },
                unhighlight: function (input) {
                    $(input).parents('.form-line').removeClass('error');
                },
                errorPlacement: function (error, element) {
                    $(element).parents('.form-group').append(error);
                }
            });
        });
    </script>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        @include('partials.alerts')
        <!-- Customers List -->
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>
                        User
                        </h2>


                    </div>


                    <div class="body">
                        <div class="row">
                            <div class="col-md-12">
                                <a href="{{ route('user.create') }}" class="btn btn-success pull-right">New User</a>
                            </div>
                        </div>
                        <table class="table table-bordered table-striped table-hover js-basic-example dataTable">
                            <thead>
                            <tr>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                           
                            <tbody>
                            @forelse ($users as $user)
                                <tr>
                                    <td>{{ $user->name }}</td>
                                    <td>{{ $user->email }}</td>
                                    <td>
                                    <form method="POST" action="{{route('user.destroy',$user->id)}}" accept-charset="UTF-8">
                                    {{ csrf_field() }}    
                                    <input name="_method" type="hidden" value="DELETE">
                                    <a href="{{route('user.edit',$user->id)}}" class="btn btn-warning waves-effect">Edit</a>
                                   
                                    <button type="submit" class="btn btn-warning waves-effect">Delete</button>
                                    </form>    
                                     </td>                                    
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">No Record Found!</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <!-- #END# Basic Examples -->
    </div>
@endsection